plot_configurations = {
    "PROTON": {
        "label_x": "$m_N$",
        "label_y": "$N$",
        "file_name": "proton_mass",
        "quark_content": "$uud$",
        "mass": "938",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S016/2024",
        "width": 0,
    },
    "LAMBDA": {
        "label_x": "$m_\\Lambda$",
        "label_y": "$\\Lambda$",
        "file_name": "lambda_mass",
        "quark_content": "$uds$",
        "mass": "1115.683",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S018/2024",
        "width": 0.006,
    },
    "SIGMA": {
        "label_x": "$m_\\Sigma$",
        "label_y": "$\\Sigma$",
        "file_name": "sigma_mass",
        "quark_content": "$uus$",
        "mass": "1189.37",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S019/2024",
        "width": 0.07,
    },
    "XI": {
        "label_x": "$m_\\Xi$",
        "label_y": "$\\Xi$",
        "file_name": "xi_mass",
        "quark_content": "$uss$",
        "mass": "1321.71",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S022/2024",
        "width": 0.07,
    },
    "DELTA": {
        "label_x": "$m_\\Delta$",
        "label_y": "$\\Delta$",
        "file_name": "delta_mass",
        "quark_content": "$uuu$",
        "mass": "1232",
        "spin_parity": "$\\frac{3}{2}^+$",
        "pdg_identifier": "B033/2024",
        "width": 120,
    },
    "SIGMA_STAR": {
        "label_x": "$m_{\\Sigma^*}$",
        "label_y": "$\\Sigma^*$",
        "file_name": "sigma_star_mass",
        "quark_content": "$uus$",
        "mass": "1384",
        "spin_parity": "$\\frac{3}{2}^+$",
        "pdg_identifier": "B043/2024",
        "width": 36,
    },
    "XI_STAR": {
        "label_x": "$m_{\\Xi^*}$",
        "label_y": "$\\Xi^*$",
        "file_name": "xi_star_mass",
        "quark_content": "$uss$",
        "mass": "1533",
        "spin_parity": "$\\frac{3}{2}^+$",
        "pdg_identifier": "B049/2024",
        "width": 9,
    },
    "OMEGA": {
        "label_x": "$m_\\Omega$",
        "label_y": "$\\Omega$",
        "file_name": "omega_mass",
        "quark_content": "$sss$",
        "mass": "1672.45",
        "spin_parity": "$\\frac{3}{2}^+$",
        "pdg_identifier": "S024/2024",
        "width": 0.29,
    },
    "D": {
        "label_x": "$m_D$",
        "label_y": "$D$",
        "file_name": "D_mass",
        "quark_content": "$c\\bar{u}$",
        "mass": "1864.84",
        "spin_parity": "$0^-$",
        "L": "S",
    },
    "D_S": {
        "label_x": "$m_{D_s}$",
        "label_y": "$D_s$",
        "file_name": "D_S_mass",
        "quark_content": "$c\\bar{s}$",
        # "mass": "1968.34",
        # "mass": "1962.9",
        "mass": "1966.7",
        "spin_parity": "$0^-$",
        "L": "S",
    },
    "ETA_C": {
        "label_x": "$m_c$",
        "label_y": "$\\eta_{c}$",
        "file_name": "ETA_C_mass",
        "quark_content": "$c\\bar{c}$",
        "mass": "2970",
        "spin_parity": "$0^-$",
        "L": "S",
    },
    "D_STAR": {
        "label_x": "$m_{D^*}$",
        "label_y": "$D^*$",
        "file_name": "D_STAR_mass",
        "quark_content": "$c\\bar{u}$",
        "mass": "2006.85",
        "spin_parity": "$1^-$",
        "L": "S",
    },
    "DS_STAR": {
        "label_x": "$m_c$",
        "label_y": "$D_s^*$",
        "file_name": "DS_STAR_mass",
        "quark_content": "$c\\bar{s}$",
        "mass": "2112.2",
        "spin_parity": "$1^-$",
        "L": "S",
    },
    "JPSI": {
        "label_x": "$m_c$",
        "label_y": "$J/\\psi$",
        "file_name": "JPSI_mass",
        "quark_content": "$c\\bar{c}$",
        "mass": "3090.1",
        "spin_parity": "$1^-$",
        "L": "S",
    },
    "D0_STAR": {
        "label_x": "$m_c$",
        "label_y": "$D_0^{*}$",
        "file_name": "D0_STAR_mass",
        "quark_content": "$c\\bar{u}$",
        "mass": "2318",
        "spin_parity": "$0^+$",
    },
    "DS0_STAR": {
        "label_x": "$m_c$",
        "label_y": "$D_{s0}^{*}$",
        "file_name": "DS0_STAR_mass",
        "quark_content": "$c\\bar{s}$",
        "mass": "2317.7",
        "spin_parity": "$0^+$",
    },
    "CHI_C0": {
        "label_x": "$m_c$",
        "label_y": "$\\chi_{c0}$",
        "file_name": "CHI_C0_mass",
        "quark_content": "$c\\bar{c}$",
        "mass": "3414.71",
        "spin_parity": "$0^+$",
        "L": "P",
    },
    "CHI_C1": {
        "label_x": "$m_c$",
        "label_y": "$\\chi_{c1}$",
        "file_name": "CHI_C1_mass",
        "quark_content": "$c\\bar{c}$",
        "mass": "3510.66",
        "spin_parity": "$1^+$",
        "L": "P",
    },
    "H_C": {
        "label_x": "$m_c$",
        "label_y": "$h_c$",
        "file_name": "H_C_mass",
        "quark_content": "$c\\bar{c}$",
        "mass": "3525.38",
        "spin_parity": "$1^+$",
        "L": "P",
    },
    "LAMBDA_C": {
        "label_x": "$m_{\\Lambda_c}$",
        "label_y": "$\\Lambda_c$",
        "file_name": "LAMBDA_C_mass",
        "quark_content": "$udc$",
        "mass": "2286.46",
        "spin_parity": "$\\frac{1}{2}^+$",
        "width": 0,
    },
    "SIGMA_C": {
        "label_x": "$m_{\\Sigma_c}$",
        "label_y": "$\\Sigma_c$",
        "file_name": "SIGMA_C_mass",
        "quark_content": "$uuc$",
        "mass": "2453.97",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "B104/2024",
        "width": 2.3,
    },
    "XI_C": {
        "label_x": "$m_c$",
        "label_x": "$m_{\\Xi_c}$",
        "label_y": "$\\Xi_c$",
        "file_name": "XI_C_mass",
        "quark_content": "$usc$",
        "mass": "2467.71",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S045/2024",
        "width": 0,
    },
    "XI_C_PRIME": {
        "label_x": "$m_{\\Xi_c'}$",
        "label_y": "$\\Xi_c'$",
        "file_name": "XI_C_PRIME_mass",
        "quark_content": "$usc$",
        "mass": "2567.71",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S045/2024",
        "width": 0,
    },
    "XI_CC": {
        "label_x": "$m_{\\Xi_{cc}}$",
        "label_y": "$\\Xi_{cc}$",
        "file_name": "XI_CC_mass",
        "quark_content": "$ucc$",
        "mass": "3621.4",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S065/2024",
        "width": 0,
    },
    "OMEGA_C": {
        "label_x": "$m_c$",
        "label_y": "$\\Omega_c$",
        "file_name": "OMEGA_C_mass",
        "quark_content": "$ssc$",
        "mass": "2695.2",
        "spin_parity": "$\\frac{1}{2}^+$",
        "pdg_identifier": "S047/2024",
        "width": 0,
    },
    "OMEGA_CC": {
        "label_x": "$m_c$",
        "label_y": "$\\Omega_{cc}$",
        "file_name": "OMEGA_CC_mass",
        "quark_content": "$scc$",
        "mass": "-1",
        "spin_parity": "$\\frac{1}{2}^+$",
        "width": 0,
    },
    "SIGMA_STAR_C": {
        "label_x": "$m_{\\Sigma^*_c}$",
        "label_y": "$\\Sigma_c^*$",
        "file_name": "SIGMA_STAR_C_mass",
        "quark_content": "$uuc$",
        "mass": "2517.9",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 17.2,
    },
    "XI_STAR_C": {
        "label_x": "$m_{\\Xi^*_c}$",
        "label_y": "$\\Xi_c^*$",
        "file_name": "XI_STAR_C_mass",
        "quark_content": "$usc$",
        "mass": "2645.1",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 2.35,
    },
    "OMEGA_STAR_C": {
        "label_x": "$m_c$",
        "label_y": "$\\Omega_c^{*}$",
        "file_name": "OMEGA_STAR_C_mass",
        "quark_content": "$ssc$",
        "mass": "2765.9",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 0,
    },
    "XI_STAR_CC": {
        "label_x": "$m_{\\Xi^*_{cc}}$",
        "label_y": "$\\Xi_{cc}^*$",
        "file_name": "XI_STAR_CC_mass",
        "quark_content": "$ucc$",
        "mass": "-1",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 0,
    },
    "OMEGA_STAR_CC": {
        "label_x": "$m_c$",
        "label_y": "$\\Omega_{cc}^{*}$",
        "file_name": "OMEGA_STAR_CC_mass",
        "quark_content": "$scc$",
        "mass": "-1",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 0,
    },
    "OMEGA_CCC": {
        "label_x": "$m_c$",
        "label_y": "$\\Omega_{ccc}$",
        "file_name": "OMEGA_CCC_mass",
        "quark_content": "$ccc$",
        "mass": "-1",
        "spin_parity": "$\\frac{3}{2}^+$",
        "width": 0,
    },
}
